### ISSUE TITLE
Some experimental details about parameter setting

### ISSUE THREAD

**Issue by wusw14** [vanzytay/KDD2018_MPCN#10]
Hi, thanks for sharing your implementation.
I tried to reuse your code on Amazon datasets, but I didn't get the performance as expected.
I tried to use Glove pretrained embedding at first and then randomly initialize the embeddings.
For the max length of each review, I firstly used the number covering 90% lengths but later set the maximum length as 50.
I doubt whether I made some mistakes in parameter settings.

**Comment by vanzytay** [comment]
Hey there. If what I recall is right. There is no pretrained embeddings used. Max length of each review is around 20-30. And each user has about 20-30 reviews. I don't recall the numbers on top of my head. Hope this helps.
