### ISSUE TITLE
Are the results in your paper the average of the results under different seeds?

### ISSUE THREAD

**Issue by heymyNLI** [vanzytay/KDD2018_MPCN#11]
Hi,
      I've read a lot of your papers and some of them are excellent ideas.
      I would like to ask whether the results reported in your paper are the results under seed 1337 or the average of the results of other multiple seeds?  I noticed that a lot of your projects use seed 1337.

**Comment by heymyNLI** [comment]
The question is just out of curiosity. 
The random seeds in deep learning would bring fluctuations to the model results. So I'd like to ask how your model behaves under other seeds?

**Comment by vanzytay** [comment]
Hey there,

1337 is just an artifact and default value of all my codebases. I don't remember how 1337 came about but i probably started using some other person's codebase with 1337 seed initially. that's all the number stuck everywhere. also some of my codebases come from the same private repo which i extracted a slice to release on github. 

In general, I don't really pay attention to the seed actually. I believe this seed only controls python's random number generator and not TF or the deep learning framework as I still observe different values for different runs (not very sure about this...).
