### ISSUE TITLE
Does a sample of (user reviews, item reviews, rating) contains the review wrote by user for item?

### ISSUE THREAD

**Issue by winterant** [vanzytay/KDD2018_MPCN#12]
For example, a sample (user reviews, item reviews, rating) represented the input for model MPCN obviously exists a review wrote by such user for such item. As TransNets mentioned, that review should not be present in development and test. I also saw that "We would like to emphasize that, when building user and item representations using their respective reviews, all reviews belonging to interactions from the test and development sets were not included." in section 4.1 of your paper. But I didn't find out how to deal with the above problem in your code. Could you give me some enlightenment?

I apologize for disturbing you if it's a problem too easy.

**Comment by vanzytay** [comment]
Hey. There are mainly two processes - split and then prep. In split, we already split the datasets which are then used to seperate reviews from train/test/dev splits. you can tell in the split script that train and test/dev reviews are being saved at different files. So when we load them, only reviews from train interactions are used to build the user/item representation. 

I haven't looked at this codebase for almost 2 years now. But i took a quick glimpse just now and can confirm that the test/dev reviews are not included.

**Comment by winterant** [comment]
Thanks!!!

I get it.

I'm very interested in this codebase and corresponding paper. So I have implemented MPCN using PyTorch (https://github.com/zhaojinglong/MPCN) to help me understand it deeply.
