### ISSUE TITLE
Can you share running instructions and code for data prep?

### ISSUE THREAD

**Issue by Plissmile** [vanzytay/KDD2018_MPCN#2]
Hi!

Thanks for sharing your great work!

Can you share your running instructions and code for data prep? Would be extremely helpful!

Thanks so much :)

**Comment by vanzytay** [comment]
Hey thanks for the interest!

I'll try to do that soon!!

**Comment by vanzytay** [comment]
@Plissmile Added the prep folder and an example prep script for yelp (let me know if you really need Amazon). I'll work on instructions when I get more free time.

**Comment by Plissmile** [comment]
Thank you~ Can you share the code for splitting yelp?

**Comment by vanzytay** [comment]
@Plissmile  Pushed.

**Comment by Plissmile** [comment]
Thank you very much!
