### ISSUE TITLE
Can you share the data prep of the Amazon

### ISSUE THREAD

**Issue by yarujin** [vanzytay/KDD2018_MPCN#3]
Hi,
I am working on the Amazon data set. Can you share the data prep of the Amazon? It will be very helpful to me.
Thank you very much.

**Comment by vanzytay** [comment]
Hey @yarujin. I have pushed amazon scripts!

**Comment by yarujin** [comment]
> Hey @yarujin. I have pushed amazon scripts!

Thank you very much for your sharing.
