### ISSUE TITLE
About hierarchical inputs

### ISSUE THREAD

**Issue by srtianxia** [vanzytay/KDD2018_MPCN#4]
Hi,
Very brilliant job! I tried to understand your code, but I have some problems.
https://github.com/vanzytay/KDD2018_MPCN/blob/6531358f73f1a6c1d613c0fcf8fd90fd75e1a40c/tylib/lib/nn.py#L209
``` _dims = embed.get_shape().as_list()[2]
    embed = tf.reshape(embed, [-1, smax, _dims])
    lengths = tf.reshape(lengths, [-1])
    return embed, lengths
```
I think the code here is different from the comments. 
In the code ,the embed should be  [bsz x (num_docs * seq_len) x dim] => [(bsz * num_docs) x seq_len x dim] and `lengths tensor` also seems to have a problem. You mentioned in the article that it is not a combination of comments into documents, but a hierarchical structure, but I found that your `lengths tensor` does not seem to be used.

Thanks !

**Comment by vanzytay** [comment]
This is due to legacy comments. Here sequence length may or may not be inclusive of docs.  Semantically,  I agree that there shld be a distinguishment between seqlen for docs level and word level. Lengths are not used but reshaped for potential future use. Hope this helps.
