### ISSUE TITLE
About some bug in prep_amazon2.py

### ISSUE THREAD

**Issue by x4x5c5** [vanzytay/KDD2018_MPCN#5]
Hi! Thanks for share your work. when I run prep_amazon2.py, it don't work.
NameError: name 'build_word_index' is not defined
Can you share this file.
Thank you!

**Comment by vanzytay** [comment]
sure! will get back soon on this!

**Comment by x4x5c5** [comment]
The same Bug in train.py
self.max_val, self.min_val, self.args.data_link = get_rec_config(self.args.dataset)
NameError: name 'get_rec_config' is not defined

**Comment by zhenchengchang** [comment]
i have a same question

**Comment by BrainyGril** [comment]
Hi! Thanks for share your work In Github. when I run prep_amazon2.py and train.py, it don't work.
NameError: name 'build_word_index' and 'tylib_tokenize' and 'build_embeddings' are not defined
NameError: name name  'get_rec_config'is not defined' are not defined
Can you share theses files.
Thank you!

**Comment by BrainyGril** [comment]
你们都解决了吗？？同志们？？？有谁解决了的，我快疯了，老铁帮帮忙呗

**Comment by vanzytay** [comment]
Have uploaded missing dependencies!
