### ISSUE TITLE
Some issues about prep_amazon2.py and train.py

### ISSUE THREAD

**Issue by BrainyGril** [vanzytay/KDD2018_MPCN#6]
Hi! Thanks for share your work In Github. when I run prep_amazon2.py and train.py, it don't work.
NameError: name 'build_word_index' and 'tylib_tokenize' are not defined
NameError: name name 'get_rec_config'is not defined' are not defined
Can you share theses files.
Thank you!

**Comment by vanzytay** [comment]
They are missing some internal libs, I'll update it soon when I have some free time. Hopefully this weekend. Thanks for your patience!

**Comment by BrainyGril** [comment]
Thank you for replying to me so soon, otherwise I will go crazy

**Comment by BrainyGril** [comment]
I saw the code and found that the model on GitHub is not from this article. Could you please re-publish this code




------------------ 原始邮件 ------------------
发件人: "Yi Tay"<notifications@github.com>; 
发送时间: 2019年7月3日(星期三) 下午4:43
收件人: "vanzytay/KDD2018_MPCN"<KDD2018_MPCN@noreply.github.com>; 
抄送: "Brainy"<2011471139@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vanzytay/KDD2018_MPCN] Some issues about prep_amazon2.py andtrain.py (#6)




They are missing some internal libs, I'll update it soon when I have some free time. Hopefully this weekend. Thanks for your patience!

**Comment by vanzytay** [comment]
@BrainyGril this is the model from the kdd paper.

**Comment by vanzytay** [comment]
@BrainyGril it would be great if you could let me me know which part you are confused about. I understand reading paper and code might not be easy. So do let me know which parts are confusing so I can update the code with appropriate comments.
