### ISSUE TITLE
other project 

### ISSUE THREAD

**Issue by WanphiaYu** [vanzytay/KDD2018_MPCN#7]
I read your paper Reasoning_ with Sarcasm by Reading In-between in ACL2018. I deal with the dataset Reddit ,and I can't get the similar results.I hope that you can share me the source code inlcuding the dataset.Thank you very much!

**Comment by WanphiaYu** [comment]
？

**Comment by vanzytay** [comment]
Thanks for your interest in the other project. There are no current plans to release code for that other paper as I have been quite busy with personal matters recently. 

Closing because of irrelevance to the KDD paper/github.
