### ISSUE TITLE
Some problems in train.py

### ISSUE THREAD

**Issue by liyushihaoren2** [vanzytay/KDD2018_MPCN#8]

**Comment by liyushihaoren2** [comment]
I can't find the function 'save_qual_data' used in train.py . So can you share it? Thanks

**Comment by vanzytay** [comment]
Sure. I am at conference now but will push it when I get back next week!!

**Comment by liyushihaoren2** [comment]
Thanks




------------------ 原始邮件 ------------------
发件人: "Yi Tay"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 晚上7:22
收件人: "vanzytay/KDD2018_MPCN"<KDD2018_MPCN@noreply.github.com>; 
抄送: "洛克西德马丁"<851064089@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vanzytay/KDD2018_MPCN] Some problems in train.py (#8)




Sure. I am at conference now but will push it when I get back next week!!
